### ISSUE TITLE
搭建 github pages

### ISSUE THREAD

**Issue by seolas** [seolas/my-notebook#5]
- 下载并安装 Node.js，msi 格式的安装包会自动添加环境变量：https://nodejs.org/zh-cn/download/
- github 新建一个空仓库 `seolas.github.io`
- 执行  `npm install -g hexo-cli`
- 本地新建一个空目录 `seolas.github.io`
- 进入目录，执行 `npm install` 
- 执行 `hexo init`
- 下载主题：https://github.com/fluid-dev/hexo-theme-fluid/tags ，解压后改名为 fluid 放到 themes 文件夹下
- 配置 token：Settings》Personal access tokens
- 改 seolas.github.io\_config.yml 文件
```
post_asset_folder: true
theme: fluid
deploy:
  type: git
  repo: https://github.com/seolas/seolas.github.io.git
  branch: main
  token: xxx
```
- 改 seolas.github.io\themes\fluid\_config.yml 文件
```
  statistics:
    enable: true
```
- 执行 `hexo new post article-name` 新建文章
- 执行 `hexo g` `hexo server`，访问 http://localhost:4000/ 本地预览
- 执行 `hexo g -d` 发布，访问 https://seolas.github.io/
